joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  controller_list:
    - name: arm_contoller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints: ['joint_1', 'joint_2', 'joint_3', 'joint_4', 'joint_5', 'joint_6']
